#!/usr/bin/env bash

set -euo pipefail

cppcheck \
    --enable=all \
    --suppress=missingIncludeSystem \
    --suppress=unusedFunction  \
    "$WD/src" \
    | sed 's/ \.\.\.//g'
for x in c h; do
    clang-format -i -verbose "$WD/src"/*."$x"
done
for x in "$WD/src"/*.hs; do
    echo "Checking $x"
    hlint "$x"
    echo "Formatting $x"
    ormolu -m inplace "$x"
done

(
    flags=(
        -fdiagnostics-color=always
        -fprof-auto-top
        -funbox-strict-fields
        -O
        -outputdir "$WD/build"
        -prof
        -Wall
        -Wcompat
        -Werror
        -Widentities
        -Wincomplete-record-updates
        -Wincomplete-uni-patterns
        -with-rtsopts "-A512m -pa"
        -Wmonomorphism-restriction
        -Wpartial-fields
        -Wredundant-constraints
        -Wunused-packages
        -Wunused-type-patterns
    )
    files=(
        "pcg_random.c"
        "Main.hs"
    )
    (
        cd "$WD/src"
        ghc "${flags[@]}" -o "$WD/bin/main" "${files[@]}"
    )
    (
        if [ ! -f "$WD/data/corpus.txt" ]; then
            wget \
                -O "$WD/data/corpus.txt" \
                "http://www.gutenberg.org/files/10/10-0.txt"
        fi
        printf "\n"
        "$WD/bin/main" "$WD/data/corpus.txt"
    )
)
