#!/usr/bin/env bash

set -euo pipefail

cppcheck \
    --enable=all \
    --suppress=missingIncludeSystem \
    --suppress=unusedFunction  \
    "$WD/src" \
    | sed 's/ \.\.\.//g'
for x in c h; do
    clang-format -i -verbose "$WD/src"/*."$x"
done
for x in "$WD/src"/*.hs; do
    echo "Checking $x"
    hlint "$x"
    echo "Formatting $x"
    ormolu -m inplace "$x"
done

(
    flags=(
        -fdiagnostics-color=always
        -outputdir "$WD/build"
        -prof
        -rtsopts
        -Wall
        -Wcompat
        -Werror
        -Widentities
        -Wincomplete-record-updates
        -Wincomplete-uni-patterns
        -Wmonomorphism-restriction
        -Wpartial-fields
        -Wredundant-constraints
        -Wunused-packages
        -Wunused-type-patterns
    )
    files=(
        "pcg_random.c"
        "Main.hs"
    )
    (
        cd "$WD/src"
        ghc "${flags[@]}" -o "$WD/bin/main" "${files[@]}"
    )
    "$WD/bin/main" +RTS -pa -RTS "$WD/data/lines.txt"
)
